import React from "react";
import WeekendIcon from "@material-ui/icons/Weekend";
function Booking() {
  const renderChair = () => {
    return <WeekendIcon style={{ color: "orange" }} />;
  };
  return (
    <div className="row">
      <div className="col-md-8">
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />{" "}
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
        <WeekendIcon style={{ color: "orange" }} />
      </div>
      <div className="col-md-4"></div>
    </div>
  );
}

export default Booking;
