export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const GET_MOVIE_2 = "GET_MOVIE_2";
export const GET_LIST_CUM_RAP = "GET_LIST_CUM_RAP";
export const LAY_THONG_TIN_LICH_CHIEU_PHIM = "LAY_THONG_TIN_LICH_CHIEU_PHIM";
