export const GET_LIST_HE_THONG_RAP = "GET_LIST_HE_THONG_RAP";
export const LAY_THONG_TIN_LICH_CHIEU_RAP = "LAY_THONG_TIN_LICH_CHIEU_RAP";
export const LAY_DANH_SASH_CUM_RAP = "LAY_DANH_SASH_CUM_RAP";
export const CHON_RAP = "CHON_RAP";
export const LAY_TT_LICH_CHIEU_PHIM = "LAY_TT_LICH_CHIEU_PHIM";
